app_ver: 0.0.1
app:
  logo: "icons/sun-logo.png"
  default_avatar: "icons/avatar-02.jpg"
datetime:
  current_year: 2020
REGEX:
  model:
    subject:
      name: !ruby/regexp "/\\A[a-zA-Z][A-Za-z \\d_]*\\z/i"
    user:
      email: !ruby/regexp "/\\A[\\w+\\-.]+@[a-z\\d\\-]+(\\.[a-z\\d\\-]+)*\\.[a-z]+\\z/i"
validates:
  model:
    subject:
      name:
        max_length: 50
        min_length: 3
      duration:
        min: 0
      image:
        content_type: /%w(image/jpeg image/gif image/png image/jpg)/
        max_size:
          MB: 5
      note:
        max_length: 120
      task_min_size: 1
    user:
      name:
        max_length: 50
      email:
        max_length: 255
      pwd:
        min_length: 6
    task:
      name:
        min_length: 5
        max_length: 50
    course:
      min_length: 6
      max_length: 255
      image:
        content_type: image/jpeg, image/png
        max_size: 1
        width: 200
        height: 200
      date_format: "%d-%m-%Y"
pagination:
  subject:
    default: 10
  course:
    default: 5
roles:
  trainee: 0
  trainer: 1
views:
  trainers:
    subjects:
      form:
        duration_min: 0.25
        duration_max: 30.0
        duration_step: 0.25
  progress:
    min: 0
    max: 100
    precision: 2
status:
  user_course_subject:
    done: 1
    doing: 0
  course:
    deleted: 0
    finished: 1
    postponed: 2
    opening: 3
report:
  limit_record: 5
